const { v4 } = require('uuid');

const drinkList = [
  {
    id: v4(),
    srcImg: 'drink/drink1.png',
    name: 'Bia 333',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 49000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink2.png',
    name: '7Up Lon',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 29000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink3.png',
    name: 'Bia Tiger',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink1.png',
    name: 'Bia 333',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 49000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink2.png',
    name: '7Up Lon 2',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 29000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink3.png',
    name: 'Bia Tiger',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'drink/drink1.png',
    name: 'Bia 333',
    type: 'one1',
    quantity: 1,
    score_fields: 5,
    cost: 49000,
    desc: '',
  },
];

export default drinkList;
