import { v4 } from 'uuid';

const pizzaList = [
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào 2',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào 2',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào 2',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào 3',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
  {
    id: v4(),
    srcImg: 'pizza.png',
    name: 'Pizza Hải Sản Đào',
    type: 'one1',
    quantity: 1,
    size: '',
    score_fields: 5,
    cost: 69000,
    desc: '',
  },
];

export default pizzaList;
